name: suggester
description: Autocompletion engine with highly configurable partial matching. Suitable for web or mobile.
version: 0.9.2
homepage: https://github.com/derbec/suggester

environment:
  sdk: ">=2.12.4 <3.0.0"

dependencies:
  meta: ^1.3.0
  collection: ^1.15.0
  ternarytreap: ^2.0.2

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
