name: suggester
description: Autocompletion engine.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  collection: ^1.14.12
  ternarytreap: ^1.0.8
dev_dependencies:
  pedantic: ^1.9.1
  test: ^1.15.2
