name: suggester
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  ternarytreap:
    path: ../ternarytreap

dev_dependencies:
  pedantic: ^1.8.0
  effective_dart: ^1.2.0
  test: ^1.6.0
